# Generated by Django 3.1.3 on 2020-11-09 04:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_identity_document', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_person', models.CharField(choices=[('IND', 'Individual'), ('LEG', 'Legal')], max_length=3)),
                ('single_taxpayer_register', models.CharField(max_length=13)),
                ('contact_name', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=9)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NPF', 'Non Perishable Foods'), ('PEF', 'Perishable Foods'), ('TLT', 'Toiletries'), ('HYG', 'Hygiene Items'), ('ACC', 'Accept Cards'), ('DGW', 'Digital Wallet'), ('PTF', 'Pet Food'), ('BAG', 'Bank Agent')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_taxpayer_register', models.CharField(max_length=13)),
                ('contact_name', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=9)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('products_or_services', models.ManyToManyField(to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('PRE', 'On preparation'), ('RTP', 'Ready to be picked up'), ('DLV', 'Delivered')], max_length=3)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.beneficiary')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.donor')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partner')),
            ],
        ),
    ]
